Medianet.Contacts.Web/Medianet.Contacts.Web/ViewModels/Outlet/OutletBaseViewModel.cs
using Medianet.Contacts.Wcf.DataContracts.DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Medianet.Contacts.Web.ViewModels.Outlet
{
    public class OutletBaseViewModel
    {
        public string Name { get; set; }
        public RecordType Type { get; set; }
        public string OutletId { get; set; }
        public string ContactId { get; set; }
        public bool IsGeneric { get; set; }
    }
}

Medianet.Contacts.Web/Medianet.Contacts.Web/ViewModels/Outlet/OutletSuggestViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Medianet.Contacts.Web.ViewModels.Outlet
{
    public class OutletSuggestViewModel
    {
        public string Name { get; set; }

        public string Id { get; set; }

        public bool IsPrivate { get; set; }

        public int RecordType { get; set; }
    }
}

Medianet.Contacts.Web/Medianet.Contacts.Web/ViewModels/Outlet/OutletViewModel.cs
using System.Collections.Generic;
using Medianet.Contacts.Web.Common.Model;

namespace Medianet.Contacts.Web.ViewModels.Outlet
{
    public class OutletViewModel : ContactOutletBaseViewModel
    {
        public string Name { get; set; }
        public string Circulation { get; set; }
        public int? Audience { get; set; }

        public int? Readership { get; set; }

        public string Bio { get; set; }
        public OutletViewModel ParentOutlet { get; set; }
        public MediaType MediaType { get; set; }
        public string PublishedOn { get; set; }
        public string Deadlines { get; set; }
        public string LogoFileName { get; set; }
        public string CopyPrice { get; set; }
        public OutletFrequency Frequency { get; set; }
        public Demographics OutletDemographics { get; set; }
        public int? MediaInfluencerScore { get; set; }
        public ICollection<Language> Languages { get; set; }
        public ICollection<ContactBase> Contacts { get; set; }
        public bool IsGeneric {get;set;}

        public string YearEstablished { get; set; }

        public string NewsFocusName { get; set; }

        public string CallLetters { get; set; }

        public string TrackingReference { get; set; }

        public string NamePronunciation { get; set; }

        public bool SubscriptionOnlyPublication { get; set; }

        public string AlsoKnownAs { get; set; }

        public string AdditionalWebsite { get; set; }

        public string BroadcastTime { get; set; }

        public string PressReleaseInterests { get; set; }

        public string RegionsCovered { get; set; }

        public string PriorityNotice { get; set; }

        public bool IsActive { get; set; }

        public List<MediaContactsService.MediaOutletPartial> RelatedMediaOutlets { get; set; }

        public List<MediaContactsService.MediaOutletPartial> SyndicatingToMediaOutlets { get; set; }
        
        public List<MediaContactsService.MediaOutletPartial> SyndicatedFromMediaOutlets { get; set; }

        public List<MediaContactsService.MediaOutletPartial> MediaOwnerOutlets { get; set; }
    }
}

Medianet.Contacts.Web/Medianet.Contacts.Web/Controllers/NoteController.cs
using System;
using System.Data;
using System.Linq;
using System.Web.Mvc;
using Medianet.Contacts.Web.Filters;
using System.Collections.Generic;
using System.Net;
using Medianet.Contacts.Web.Services.Note;
using Medianet.Contacts.Wcf.DataContracts.DTO;
using Medianet.Contacts.Web.Common.Model;
using Medianet.Contacts.Web.ViewModels.List;
using Medianet.Contacts.Web.Services.List;
using Medianet.Contacts.Web.ViewModels.Note;
using System.Web.UI;

namespace Medianet.Contacts.Web.Controllers
{
    public class NoteController : BaseController
    {
        private readonly INoteService _noteService;

        public NoteController() : base()
        {
            _noteService = NoteService.CreateNoteService();
        }
        
        [HandleAjaxError, HandleAjaxAuthorization]
        public PartialViewResult PinnedNotes(string contactId, string outletId, string recordType)
        {
            var paginatesNotes = GetNotes(contactId, outletId, recordType, true);
            paginatesNotes.Pagination.CalculatePagination();
            paginatesNotes.Pagination.CurrentPageOnly = true;
            
            return PartialView("Note/_PinnedNotesPartial", paginatesNotes);
        }
        
        [HandleAjaxError, HandleAjaxAuthorization]
        public PartialViewResult UnPinnedNotes(string contactId, string outletId, string recordType)
        {
            var paginatesNotes = GetNotes(contactId, outletId, recordType, false);
            paginatesNotes.Pagination.CalculatePagination();
            paginatesNotes.Pagination.CurrentPageOnly = true;

            return PartialView("Note/_UnPinnedNotesPartial", paginatesNotes);
        }

        [OutputCache(Location = OutputCacheLocation.None)]
        [HandleAjaxAuthorization, HandleAjaxError]
        public ActionResult Rebind(string contactId, string outletId, string recordType, bool pinned, PaginationNoteViewModel model)
        {
            // Calculate pagination.
            model.CalculatePagination();

            // Get the current page.
             List<NoteViewModel> results = GetCurrentPagedNote(contactId, outletId, recordType, pinned, model.Page);
            model.Notes= results;

            if (model.ResultCount > ((model.Page - 1) * model.PageSize))
            {
                ; //@ ok
            }
            else
            {
                //@ may be we have deleted items and we need to go to the last page
                model.Page = 1 + (model.ResultCount / model.PageSize);
                results = GetCurrentPagedNote(contactId, outletId, recordType, pinned, model.Page);
                model.Notes = results;
                model.CalculatePagination();
            }

            // This prevents the form data from persisting.
            ModelState.Clear();

            var notes = new NoteResultsViewModel
            {
                Pagination = model,
            };
            
            return PartialView($"Note/{(pinned ? "_PinnedNotesPartial" : "_UnPinnedNotesPartial")}", notes);
        }

        private List<NoteViewModel> GetCurrentPagedNote(string contactId, string outletId, string recordType, bool pinned, int pageNumber)
        {
            var notes = GetNotes(contactId, outletId, recordType, pinned, pageNumber);

            return notes.Pagination.Notes;
        }

        [HandleAjaxError, HandleAjaxAuthorization]
        public ActionResult DeleteNote(string id)
        {
            if (!string.IsNullOrEmpty(id))
            {
                _noteService.DeleteNote(Convert.ToInt32(id), CurrentUser.SessionKey);
            }
            else
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }

            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }
        
        [HandleAjaxError, HandleAjaxAuthorization]
        public ActionResult PinUnpinNote(string id, string pinned)
        {
            if (!string.IsNullOrEmpty(id))
            {
                _noteService.PinUnpinnNote(Convert.ToInt32(id), Convert.ToBoolean(pinned), CurrentUser.SessionKey);
            }
            else
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }

            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }

        [HttpGet]
        [HandleAjaxAuthorization, HandleAjaxError]
        public ActionResult Create(string outletId, string contactId, string recordType)
        {
            var note = new NoteViewModel
            {
                OutletId = outletId,
                ContactId = contactId,
                UserId = CurrentUser.UserID,
                DebtorNumber = CurrentUser.DebtorNumber,
                RecordType = (RecordType)Enum.Parse(typeof(RecordType), recordType.ToString())
            };

            return PartialView("Note/_AddNotePartial", note);
        }

        [HttpGet]
        [HandleAjaxAuthorization, HandleAjaxError]
        public ActionResult CreateBulk()
        {
            var note = new NoteViewModel
            {
                UserId = CurrentUser.UserID,
                DebtorNumber = CurrentUser.DebtorNumber
            };

            return PartialView("Note/_AddNotePartial", note);
        }

        [HttpGet]
        [HandleAjaxAuthorization, HandleAjaxError]
        public ActionResult Update(string id, string recordType)
        {
            var note = _noteService.GetNote(Convert.ToInt32(id), recordType, CurrentUser.SessionKey);
            return PartialView("Note/_AddNotePartial", note);
        }

        [HttpPost]
        [HandleAjaxAuthorization, HandleAjaxError]
        public ActionResult CreateUpdate(NoteViewModel note)
        {
            if (note.Id == 0)
            {
                _noteService.AddNote(note, CurrentUser.SessionKey);
            }
            else
            {
                _noteService.UpdateNote(note, CurrentUser.SessionKey);
            }

            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }

        [HttpPost]
        [HandleAjaxAuthorization, HandleAjaxError]
        public ActionResult CreateBulk(NoteViewModel note)
        {
            List<ListRecord> recordsToAdd = null;

            string[] myCheckedItems = GetItemsMergedDistinctChecked(note, ListCheckedItems);
            string[] myUncheckedItems = GetItemsMergedDistinctUnchecked(note, ListCheckedItems);

            ListResultsViewModel listItems;

            using (ListService myListService = ListService.CreateListService())
            {
                listItems = myListService.GetListItemsAll(note.ListId, note.ListSetId, CurrentUser.UserID, CurrentUser.SessionKey);
            }

            if (note.CheckboxState == CheckboxState.All)
            {
                myCheckedItems = listItems.Pagination.Results.Select(r => r.ToClientString()).ToArray();
            }
            else if (note.CheckboxState == CheckboxState.PartAll)
            {
                myCheckedItems =
                    listItems.Pagination.Results.Select(r => r.ToClientString()).Except(myUncheckedItems).ToArray();
            }

            recordsToAdd =
                new List<ListRecord>(
                    listItems.Pagination.Results.Where(r => myCheckedItems.Contains(r.ToClientString())));

            _noteService.AddNoteBulk(note, recordsToAdd, CurrentUser.SessionKey);

            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }

        private NoteResultsViewModel GetNotes(string contactId, string outletId, string recordType, bool pinned,
                                             int pageNumber = 1, int pageSize = 0)
        {
            var paginatesNotes = new NoteResultsViewModel();
            var notes = new List<NoteViewModel>();
            if (pageSize == 0)
                pageSize = paginatesNotes.Pagination.PageSize;

            if (!string.IsNullOrEmpty(contactId) && !string.IsNullOrEmpty(outletId) && recordType != null)
            {
                notes = _noteService.GetContactNotes(
                    contactId, outletId, recordType, CurrentUser.UserID, CurrentUser.SessionKey).ToList();
            }
            else if (string.IsNullOrEmpty(contactId) && !string.IsNullOrEmpty(outletId) && recordType != null)
            {
                notes = _noteService.GetOutletNotes(outletId, recordType, CurrentUser.UserID, CurrentUser.SessionKey);
            }

            notes = notes.Where(n => n.Pinned == pinned).ToList().OrderByDescending(n => n.AAPNote).ThenByDescending(n => n.CreatedDate).ToList();

            paginatesNotes.Pagination.Notes = notes.Skip((pageNumber - 1) * pageSize).Take(pageSize).ToList();
            paginatesNotes.Pagination.ResultCount = notes.Count;
            paginatesNotes.Pagination.PageSize = pageSize;
            return paginatesNotes;
        }
    }
}

Medianet.Contacts.Web/Medianet.Contacts.Web/Controllers/SocialController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Medianet.Contacts.Web.Services.Social;
using Medianet.Contacts.Web.ViewModels.Social;
using Medianet.Contacts.Web.Filters;
using System.Threading.Tasks;
using System.Web.Caching;
using System.Runtime.Caching;

namespace Medianet.Contacts.Web.Controllers
{
    public class SocialController : BaseController
    {
        private IKloutService _kloutService;
        private ITwitterService _twitterService;
        private IYouTubeService _youTubeService;
        private static readonly MemoryCache _cache = new MemoryCache("ActionResultCacheAttribute");
        private static string twitterCacheKey = "twit-prof";

        public SocialController() : base()
        {
            _kloutService = KloutService.CreateKloutService();
            _twitterService = TwitterService.CreateTwitterService();
            _youTubeService = YouTubeService.CreateYouTubeService();
        }

        //
        // GET: /Social/Klout?twitterHandle={twitterHandle}
        [HttpGet]
        public ActionResult Klout(string twitterHandle)
        {
            var model = new KloutViewModel();

            model = _kloutService.GetKloutScore(twitterHandle);

            return PartialView(model);
        }

        [HttpPost]
        [HandleAjaxAuthorization, HandleAjaxError]
        public async Task<JsonResult> MultiUsersTwitterImages(string twitterHandles)
        {
            return Json(await GetMultiTwitterDetails(twitterHandles), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        [HandleAjaxAuthorization, HandleAjaxError]
        public async Task<JsonResult> UserTwitterImage(string twitterHandle)
        {
            return Json(await GetTwitterDetails(twitterHandle), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        [HandleAjaxAuthorization, HandleAjaxError]
        public async Task<PartialViewResult> UserTwitter(string twitterHandle)
        {
            return PartialView("Social/_TwitterPartial", await GetTwitterDetails(twitterHandle));
        }
        
        [HttpGet]
        public async Task<PartialViewResult> UserTweets(string twitterHandle)
        {
            return PartialView("Social/_TweetsPartial", await _twitterService.GetUserTweets(twitterHandle));
        }

        [HttpGet]
        [HandleAjaxAuthorization, HandleAjaxError]
        public PartialViewResult UserYouTube(string url)
        {
            YouTubeViewModel result = _youTubeService.GetData(url);

            return PartialView("Social/_YouTubePartial", result);
        }

        private async Task<List<TwitterUserViewModel>> GetMultiTwitterDetails(string twitterHandles)
        {
            var handles = HttpUtility.UrlDecode(twitterHandles ?? "").Split(new[] { ',' }, StringSplitOptions.RemoveEmptyEntries);
            var handlesNotCached = "";
            var twitterDetailsList = new List<TwitterUserViewModel>();

            foreach (var item in handles)
            {
                var key = $"{twitterCacheKey}-{item.ToLower()}";
                var cachedItem = _cache.Get(key);

                if (cachedItem == null)
                    handlesNotCached += item + ",";               
                else
                {
                    twitterDetailsList.Add((TwitterUserViewModel)cachedItem);
                }
            }

            if (!string.IsNullOrEmpty(handlesNotCached))
            {
                var models = await _twitterService.GetUsersTwitterInfo(handlesNotCached);

                foreach (var item in models)
                {
                    if (!string.IsNullOrEmpty(item.ProfileImage))
                    {
                        _cache.Add($"{twitterCacheKey}-{item.Handle.ToLower()}", item, DateTime.Now.AddSeconds(3600));
                        twitterDetailsList.Add(item);
                    }
                }
            }

            return twitterDetailsList;
        }

        private async Task<TwitterUserViewModel> GetTwitterDetails(string twitterHandle)
        {
            var twitterDetails = new TwitterUserViewModel();
            var cacheKey = $"{twitterCacheKey}-{twitterHandle.ToLower()}";
            var cachedItem = _cache.Get(cacheKey);

            if (cachedItem != null)
            {
               return  (TwitterUserViewModel)cachedItem;
            }
                
            twitterDetails = await _twitterService.GetUserTwitterInfo(twitterHandle);

            if (twitterDetails != null && !string.IsNullOrEmpty(twitterDetails.ProfileImage))
            {
                _cache.Add(cacheKey, twitterDetails, DateTime.Now.AddSeconds(3600));
            }               
          
            return twitterDetails;
        }
    }
}

Medianet.Contacts.Web/Medianet.Contacts.Web/Views/Outlet/Index.cshtml
@{
    ViewBag.Title = "Outlet";
}
@using Medianet.Contacts.Wcf.DataContracts.DTO
@using Medianet.Contacts.Web.Common.Util
@model Medianet.Contacts.Web.ViewModels.Outlet.OutletViewModel
@section Javascript{
    @Scripts.Render("~/bundles/outletandcontact")
    @Scripts.Render("~/bundles/outlet")
}
@if (Model == null)
{
    <div class="alert alert-danger mt-2 mt-sm-5" role="alert">
        @ViewBag.Message
    </div>
}
else
{
    ViewBag.OutletType = (int)Model.Type;
    <div class="d-flex flex-column flex-lg-row align-items-start justify-content-between">
        <div class="mb-3 mb-lg-0">
            <h2 class="mb-0">
                @(Model.MediaType == null ? "" : Model.MediaType.Name.Trim()) Outlet

                @if (RecordTypeExtensions.IsOmaType(Model.Type))
                {
                    <a class="btn btn-link py-0" title="Edit Outlet" href="@Url.Action("Edit", "PrivateOutlet", new { Id = Model.OutletId })">
                        <i class="fal fa-fw fa-pencil"></i>
                    </a>
                }
            </h2>
            <a class="smallCaps backToSearch" href="#" id="lnkBack">back</a>
        </div>
        @Html.Partial("OutletAndContact/_ActionBarPartial", Model)
    </div>

    <div class="row mt-3" data-main-container data-recordType="@Model.Type" data-outletId="@Model.OutletId.Trim()">
        <div class="col-12 col-md-4 col-lg-3">
            @Html.Partial("_OutletDetailsPartial", Model)
            @Html.Partial("_SubjectProfilePartial", Model.Subjects)
            @{ViewBag.IsSyndicatingTo = true;}
            @Html.Partial("_MediaSyndicatedOutletsPartial", Model.SyndicatingToMediaOutlets)
            @{ViewBag.IsSyndicatingTo = false; }
            @Html.Partial("_MediaSyndicatedOutletsPartial", Model.SyndicatedFromMediaOutlets)
            @Html.Partial("_BelongToListsPartial", Model.BelongsToLists)
        </div>
        <div class="col-12 col-md-8 col-lg-6">
            @Html.Partial("_MediaType_RelatedOutletsPartial", Model)
            @if (!string.IsNullOrEmpty(Model.PriorityNotice))
            {
                <div class="card mb-4 callout">
                    <div class="card-body">
                        <h5 class="card-title text-orange">Priority Notice</h5>
                        <p class="card-text">
                            @Model.PriorityNotice
                        </p>
                    </div>
                </div>
            }
            @if (!string.IsNullOrEmpty(@Model.Bio))
            {
                <div class="card mb-4">
                    <div class="card-body">
                        <h5 class="card-title">ABOUT</h5>
                        <p class="card-text">
                            @Html.FormatBioHelper(Model.Bio)
                        </p>
                    </div>
                </div>
            }
            @Html.Partial("_OutletProfilePartial", Model)
            @Html.Partial("_MediaOwnerOutletsPartial", Model)
            @if (!string.IsNullOrEmpty(@Model.ProfileNotes))
            {
                <div class="card mb-4">
                    <div class="card-body">
                        <h5 class="card-title">Details</h5>
                        <p class="card-text">
                            @Html.FormatBioHelper(Model.ProfileNotes)
                        </p>
                    </div>
                </div>
            }

            <div class="card mb-4 outletMVContainer">
                <div class="outletMediaMovements" data-action="@Url.Action("GetOutletMediaMovements", "Outlet", new {outletId = Model.OutletId})">
                    @Html.Partial("_InlineSpinnerPartial")
                </div>
            </div>
            
            @if (Model.SocialDetails != null && Model.SocialDetails.Twitter.HasValue())
            {
                <div class="card mb-4">
                    <div class="card-body">
                        <h5 class="card-title">Latest Media</h5>
                        <ul class="nav nav-tabs justify-content-end" id="myTab" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link active" id="tweets-tab" data-toggle="tab" href="#tweets" role="tab" aria-controls="tweets" aria-selected="true">Tweets</a>
                            </li>
                        </ul>
                        <div class="tab-content tab-lists" id="myTabContent">
                            <div class="tab-pane fade show active" id="tweets" role="tabpanel" aria-labelledby="tweets-tab" data-tweets data-tweets-url="@Url.Action("UserTweets", "Social")" data-twitterhandle="@Model.SocialDetails.Twitter">
                                @Html.Partial("_InlineSpinnerPartial")
                            </div>
                        </div>
                    </div>
                </div>
            }

            @*Notes*@
            <div class="card mb-4" data-spinnercontainer="divAllNotes">
                <div class="card-body">
                    <h5 class="card-title">My Notes and Activity</h5>
                    <div data-container="pinnedNotes" data-action="@Url.Action("PinnedNotes", "Note")">
                        @Html.Partial("_InlineSpinnerPartial")
                    </div>
                    <div data-container="unPinnedNotes" data-action="@Url.Action("UnPinnedNotes", "Note")">
                        @Html.Partial("_InlineSpinnerPartial")
                    </div>
                    <div class="d-flex justify-content-end actionBtns">
                        <a class="d-flex ml-3 badge badge-pill badge-primary" href="#" data-addnote-url="@Url.Action("Create", "Note")" data-type="@PopupType.Contact">
                            <i class="fas fa-fw fa-pencil"></i>
                            <span class="align-self-start m-1">add note</span>
                        </a>
                    </div>
                </div>
                <span class="tooltip-info-icon" data-toggle="tooltip" data-placement="left"
                      title="Save notes to this record and pin priority notes to the top of the list.">
                    <i class="fas fa-info-circle"></i>
                </span>
            </div>
            @*End Of Notes*@
            @Html.Partial("~/Views/Document/_DocumentsListPartial.cshtml", Model)
        </div>

        <div class="col col-lg-3">
            @if (Model.SocialDetails != null)
            {
                @Html.Partial("Social/_SocialEngagementPartial", Model.SocialDetails)
            }
            @Html.Partial("_ContactsPartial", Model)
        </div>
    </div>
            <div class="d-flex align-items-end justify-content-between py-3 border-top">
                <div>&nbsp;</div>
                @Html.Partial("OutletAndContact/_ActionBarPartial", Model)
            </div>
                }

Medianet.Contacts.Web/Medianet.Contacts.Web/Views/Outlet/_ContactsPartial.cshtml
@model Medianet.Contacts.Web.ViewModels.Outlet.OutletViewModel
@if (Model.Contacts != null && Model.Contacts.Any())
{
    int outletContactCount = int.Parse(System.Configuration.ConfigurationManager.AppSettings["OutletContactCount"] ?? "0");
    <div class="card mb-4">
        <div class="card-body">
            <h5 class="card-title">Contacts</h5>
            <ul class="list-group list-group-flush">
    @foreach (var item in Model.Contacts.OrderByDescending(c => c.IsPrimaryNewsContact).ThenBy(c => c.Name).Take(outletContactCount))
                {
        <li class="list-group-item">
            <span class="d-flex my-2">
                @if (item.SocialDetails != null && item.SocialDetails.Twitter.HasValue())
                {
                    <img class="rounded-circle my-1 mr-2" src="/Content/Images/user_profile_avatar.png" width="44" height="44" alt="Contact avatar"
                         @("data-twitterhandle=" + item.SocialDetails.Twitter) />
                }
                else
                {
                    <span class="avatar avatar-xs my-1 mr-2">@item.Name.Initials</span>
                }

                <span class="d-flex flex-column">
                    <a href="@Url.Action("index", "Contact", new {outletId = (item.OutletId ?? string.Empty).Trim(), contactId = (item.ContactId ?? string.Empty).Trim(), recordType = (int) item.Type})">
                        @Html.PrivateIconHelper(item.Type)
                        <span class="@(item.IsPrimaryNewsContact ? "d-inline" : "d-none")" data-toggle="tooltip" data-placement="top" title="The primary contact is the main point of contact for an outlet, who would like to receive media information."><i class="fas fa-star"></i></span>
                        <b>@item.Name.FirstName @item.Name.LastName</b>
                    </a>
                    <span class="d-inline-block text-lineheight-min">
                        @item.JobTitle
                    </span>
                </span>
            </span>
        </li>
    }
</ul>
        <div class="pt-2 text-right showMoreLess">
            <a href="@Url.Action("Expand", "Search", new { outletid = (Model.OutletId ?? string.Empty).Trim(), type = (int)Model.Type, Advanced = false})">view all</a>
        </div>
        </div>
    </div>
}

Medianet.Contacts.Web/Medianet.Contacts.Web/Views/Outlet/_MediaOwnerOutletsLinkPartial.cshtml
@using Medianet.Contacts.Web.MediaContactsService
@model List<object>
@{ 
    MediaOutletPartial item = (MediaOutletPartial)Model[0];
    int index = (int)Model[1];
    int recordType = (int)Model[2];
}
<div class="@(index >= 10 ? "extra-businesses collapse" : "")">
    <a href="@Url.Action("Index", "Outlet", new { id = (item.Id ?? string.Empty).Trim(), recordType = recordType })"
       class="text-nowrap text-truncate d-block" title="@item.Name">
        @item.Name
    </a>
</div>

Medianet.Contacts.Web/Medianet.Contacts.Web/Views/Outlet/_MediaOwnerOutletsPartial.cshtml
@using Medianet.Contacts.Web.MediaContactsService
@model Medianet.Contacts.Web.ViewModels.Outlet.OutletViewModel
@if (Model.ParentOutlet == null && Model.MediaOwnerOutlets != null && Model.MediaOwnerOutlets.Any())
{
    <div class="card mb-4 businesses">
        <div class="card-body">
            <h5 class="card-title">Businesses</h5>
            <div class="card-text">
                <div class="row businesses-columns">
                    <div class="col-6">
                        @{ 
                            int firstColumnCount = (int)Math.Round((double)Model.MediaOwnerOutlets.Count / 2, MidpointRounding.AwayFromZero);
                            List<MediaOutletPartial> list = Model.MediaOwnerOutlets.Take(firstColumnCount).ToList();
                            for (int i = 0; i < list.Count; i++)
                            {
                                @Html.Partial("_MediaOwnerOutletsLinkPartial", new List<object> { list[i], i, (int)Model.Type })
                            }
                        }
                    </div>
                    @if (Model.MediaOwnerOutlets.Count >= 2)
                    {
                        list = Model.MediaOwnerOutlets.Skip(firstColumnCount).ToList();
                        <div class="col-6">
                            @for (int i = 0; i < list.Count; i++)
                            {
                                @Html.Partial("_MediaOwnerOutletsLinkPartial", new List<object> { list[i], i, (int)Model.Type })
                            }
                        </div>
                    }
                </div>
            </div>
            @if (Model.MediaOwnerOutlets.Count > 20)
            {
                <div class="showMoreLess lnk-toggle collapsed" data-toggle="collapse" data-target=".extra-businesses">
                    <a class="lnk-toggle-show">more ...</a>
                    <a class="lnk-toggle-hide">less</a>
                </div>
            }
        </div>
    </div>
}

Medianet.Contacts.Web/Medianet.Contacts.Web/Views/Outlet/_OutletMediaMovementsPartial.cshtml
@using Medianet.Contacts.Web.Common.DAL
@using Medianet.Contacts.Web.ViewModels.Dashboard

@model List<MediaMovementsViewModel>

@if (Model != null && Model.Any())
{
    var outletId = Model.Select(o => o.OutletId.ToString()).First().Trim();
    var list = Model.Take(4).ToList();

    <div class="card-body pb-2">
        <h4 class="card-title">Media Movements</h4>
          @Html.Partial("~/Views/Dashboard/_MediaMovementsPartial.cshtml", list)
    </div>
    if (Model.Count > 4)
    {
        <div class="showMoreLess pb-2 pr-2">
            <a href="@Url.Action("Outlet", "MediaMovements", new {outletId = outletId})">more...</a>
        </div>
    }
}