Medianet.Contacts.Web/Medianet.Contacts.Web/ViewModels/List/LicensesExceededViewModel.cs
using System.Collections.Generic;

namespace Medianet.Contacts.Web.ViewModels.List
{
    public class LicensesExceededViewModel
    {
        public int LicenseCount;
        public List<ChargeBeeService.DBSession> ActiveSessions;
    }
}

Medianet.Contacts.Web/Medianet.Contacts.Web/ViewModels/List/ListContactReplacementViewModel.cs
using Medianet.Contacts.Wcf.DataContracts.DTO;

namespace Medianet.Contacts.Web.ViewModels.List
{
    public class ListContactReplacementViewModel
    {
        public int RecordId { get; set; }
        public int ListSetId { get; set; }
        public int ListId { get; set; }
        public string ListName { get; set; }
        public string MediaContactId { get; set; }
        public string PrnContactId { get; set; }
        public string OmaContactId { get; set; }
        public string ContactDeletedName { get; set; }
        public string OutletDeletedName { get; set; }

        public string ContactReplacementId { get; set; }

        public string ContactReplacementName { get; set; }

        public string OutletDeletedId { get; set; }

        public int RecordType { get; set; }
    }
}

Medianet.Contacts.Web/Medianet.Contacts.Web/ViewModels/List/ListDeleteItemsViewModel.cs
using Medianet.Contacts.Wcf.DataContracts.DTO;
using Medianet.Contacts.Web.ViewModels.Grid;

namespace Medianet.Contacts.Web.ViewModels.List
{
    public class ListDeleteItemsViewModel : GridViewModelBase
    {
        public DeleteAction Type { get; set; }
        public int ListId { get; set; }
        public int ListSetId { get; set; }
    }
}

Medianet.Contacts.Web/Medianet.Contacts.Web/ViewModels/List/ListDuplicateViewModel.cs
using Medianet.Contacts.Web.Common.BO;
using System.ComponentModel.DataAnnotations;

namespace Medianet.Contacts.Web.ViewModels.List
{
    public class ListDuplicateViewModel : ListViewModel
    {
        public GroupState GroupState { get; set; }

        public int NewListId { get; set; }

        [Required(ErrorMessage = "Please enter a new list name")]
        public string NewListName { get; set; }
    }
}

Medianet.Contacts.Web/Medianet.Contacts.Web/ViewModels/List/ListMergeViewModel.cs
using Medianet.Contacts.Web.Common.BO;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace Medianet.Contacts.Web.ViewModels.List
{
    public class ListMergeViewModel : ListViewModel
    {
        public GroupState GroupState { get; set; }

        public int NewListId { get; set; }

        [Required(ErrorMessage = "Please enter a new list name")]
        public string NewListName { get; set; }

        public List<KeyValuePair<string, List<SelectListItem>>> ListsGrouped { get; set; }

        [Required(ErrorMessage = "Please select a list to merge with")]
        public List<int> ListsToMergeWith { get; set; }
    }
}

Medianet.Contacts.Web/Medianet.Contacts.Web/ViewModels/List/ListResultsViewModel.cs
namespace Medianet.Contacts.Web.ViewModels.List
{
    public class ListResultsViewModel
    {
        /// <summary>
        /// Pagination object.
        /// </summary>
        public PaginationListViewModel Pagination { get; set; }

        /// <summary>
        /// Constructor.
        /// </summary>
        public ListResultsViewModel()
        {
            Pagination = new PaginationListViewModel();
            Pagination.ResultCount = 0;
        }
    }
}

Medianet.Contacts.Web/Medianet.Contacts.Web/Controllers/OutletController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web.Mvc;
using AutoMapper;
using Medianet.Contacts.Wcf.DataContracts.DTO;
using Medianet.Contacts.Web.Filters;
using Medianet.Contacts.Web.MediaContactsService;
using Medianet.Contacts.Web.Services.Outlet;
using Medianet.Contacts.Web.ViewModels.Outlet;
using Medianet.Contacts.Web.ProxyWrappers;

namespace Medianet.Contacts.Web.Controllers
{
    public class OutletController : BaseController
    {
        #region Field

        private readonly IOutletService _outletService;

        public static string OutletNotFound { get { return "Either the Outlet does not exist or you do not have permissions to view the Outlet."; } }

        public OutletViewModel OutletViewModel { get; set; }

        #endregion

        public OutletController() : base()
        {
            _outletService = OutletService.CreateOutletService();
        }

        protected override void Dispose(bool disposing)
        {
            if (_outletService != null) _outletService.Dispose();
            base.Dispose(disposing);
        }

        [HandleHtmlError, HandleAuthentication]
        public ActionResult Index(string id, string recordType)
        {
            if (string.IsNullOrEmpty(id) && string.IsNullOrEmpty(recordType))
            {
                ViewBag.Message = OutletNotFound;
            }
            else
            {
                GetOutletDetails(id, recordType);

                if (OutletViewModel == null)
                    ViewBag.Message = OutletNotFound;
                else
                    LogOutletView(id, recordType);
            }

            return View(OutletViewModel);
        }
        
        [HandleAjaxError, HandleAjaxAuthorization]
        public PartialViewResult OutletPreview(string outletId, string recordType)
        {
            RecordType rt = (RecordType)Enum.Parse(typeof(RecordType), recordType);
            var outletViewModel = new OutletViewModel();

            if (rt == RecordType.MediaOutlet)
            {
                outletViewModel = _outletService.GetOutletPreview(outletId, (RecordType)Enum.Parse(typeof(RecordType), recordType), CurrentUser);
            }
            else {
                outletViewModel = _outletService.GetOutlet(outletId, (RecordType)Enum.Parse(typeof(RecordType), recordType), CurrentUser);
            }

            ViewBag.UserId = CurrentUser.UserID;
            return PartialView("_OutletPreviewPartial", outletViewModel);
        }

        [HandleAjaxError]
        [HandleAjaxAuthorization]
        public PartialViewResult GetOutletMediaMovements(string outletId)
        {
           var viewModel = _outletService.GetOutletMediaMovements(outletId, 1 , 5, CurrentUser);
           return PartialView("_OutletMediaMovementsPartial", viewModel);
        }

        [NonAction]
        public string GetOutletLogo(string logoFileName)
        {
            try
            {
                string path = _outletService.GetOutletLogo(logoFileName, CurrentUser);

                return path;
            }
            catch (Exception ex)
            {
                return string.Empty;
            }
        }

        #region Methods

        private OutletViewModel GetOutletDetails(string outletId, string recordType)
        {
            OutletViewModel = _outletService.GetOutlet(outletId, (RecordType)Enum.Parse(typeof(RecordType), recordType), CurrentUser);
            
            ViewBag.UserId = CurrentUser.UserID;
            return OutletViewModel;
        }

        private void LogOutletView(string outletId, string recordType)
        {
            var recordTypeEnum = (RecordType)Enum.Parse(typeof(RecordType), recordType);

            using (MediaContactsServiceProxy mediaContactsService = new MediaContactsServiceProxy())
            {
                if (recordTypeEnum == RecordType.MediaOutlet)
                {
                    mediaContactsService.LogMediaOutletView(outletId, CurrentUser.UserID, CurrentUser.SessionKey);
                }
            }
        }

        #endregion
    }
}

Medianet.Contacts.Web/Medianet.Contacts.Web/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using System.Web.UI;
using Medianet.Contacts.CSharp.ExtensionMethods;
using AutoMapper;
using Medianet.Contacts.Wcf.DataContracts.DTO;
using Medianet.Contacts.Web.Common;
using Medianet.Contacts.Web.Common.BAL;
using Medianet.Contacts.Web.Common.Model;
using Medianet.Contacts.Web.Common.Util;
using Medianet.Contacts.Web.Filters;
using Medianet.Contacts.Web.ProxyWrappers;
using Medianet.Contacts.Web.Services.List;
using Medianet.Contacts.Web.Services.Search;
using Medianet.Contacts.Web.ViewModels;
using Medianet.Contacts.Web.ViewModels.Grid;
using Medianet.Contacts.Web.ViewModels.List;
using Medianet.Contacts.Web.ViewModels.Search;
using Ninject;
using Location = Medianet.Contacts.Wcf.DataContracts.DTO.Location;
using LocationModel = Medianet.Contacts.Web.Common.Model.Location;
using Medianet.Contacts.Web.Services;
using Medianet.Contacts.Web.ViewModels.AllSavedSearches;
using System.Text.RegularExpressions;
using Medianet.Contacts.Web.Common.BO;
using Medianet.Contacts.Web.Services.Outlet;
using Medianet.Contacts.Web.Helpers;

namespace Medianet.Contacts.Web.Controllers
{
    public class SearchController : BaseController
    {
        #region Field

        public static readonly string Search_ErrorMessage = "An error has occured. Unable to perform search.";
        public static readonly string Search_InvalidSavedSearch = "The saved search either does not exist or you are not authorised to view it.";

        public static readonly int MaxAutosuggest = 100;

        private readonly IOutletService _outletService;

        // Services.
        private ISavedSearchService _savedSearchService;
        private IGroupService _groupService;
        private IListService _listService;
        private Medianet.Contacts.Web.Services.Search.SearchService _searchService;

        #endregion

        [Inject]
        public SearchController()
            : base()
        {
            _savedSearchService = SavedSearchService.CreateSavedSearchService();
            _groupService = GroupService.CreateGroupService();
            _listService = ListService.CreateListService();
            _searchService = Services.Search.SearchService.CreateSearchService();
            _outletService = OutletService.CreateOutletService();
        }

        protected override void Dispose(bool disposing)
        {
            if (_savedSearchService != null) _savedSearchService.Dispose();
            if (_groupService != null) _groupService.Dispose();
            base.Dispose(disposing);
        }

        #region Actions

        [OutputCache(Location = OutputCacheLocation.None)]
        [HandleAjaxAuthorization, HandleAjaxError, RequiresSession, SavesSession]
        public ActionResult Rebind(PaginationSearchViewModel model, bool? isSearchPage)
        {
            isSearchPage = (isSearchPage ?? true) && !new List<string> { "/privatecontact", "/privateoutlet" }.Contains(Request.UrlReferrer.AbsolutePath.ToString().ToLower());
            ViewBag.IsSearchPage = isSearchPage;
            model.UseCookieForPageSize = isSearchPage.Value;

            List<SearchResult> results = GetCurrentSearchResults(model.Expand, model.SortColumn, model.SortDirection, !isSearchPage.Value);

            // Calculate pagination.
            model.CalculatePagination();

            // Set the unselected items.
            SetUnselectedItems(model, results);

            // Get the current page.
            model.Results = GetCurrentPagedSearch(model, results);

            var current = results.Except(DeletedItems);
            if (UnselectedItems.Count() > 0)
            {
                if (model.CheckboxState == CheckboxState.PartNone)
                {
                    var SelectedItems = current.Except(UnselectedItems).ToList();

                    model.CurrentPageOnly = model.Results
                        .Except(DeletedItems)
                        .Intersect(SelectedItems).Count() == SelectedItems.Count;
                }
                else if (model.CheckboxState == CheckboxState.None)
                {
                    model.CurrentPageOnly = UnselectedItems.Count == current.Count();
                }
                else
                {
                    model.CurrentPageOnly = model.Results
                        .Except(DeletedItems)
                        .Intersect(UnselectedItems).Count() == UnselectedItems.Count();
                }
            }
            else
                model.CurrentPageOnly = true;

            // This prevents the form data from persisting.
            ModelState.Clear();

            var s = new SearchViewModel
            {
                Pagination = model,
                Context = model.Expand == "all" || SearchOptions == null ? SearchContext.People : SearchOptions.Context,
                AdvancedSearch = SearchOptions != null && SearchOptions is SearchOptionsAdvanced ? new AdvancedSearchViewModel() : null
            };

            s.Pagination.ResultCount = results.Count;

            return PartialView("_PagePartial", s);
        }

        [HttpGet]
        [SavesSession]
        [HandleHtmlError, HandleAuthentication]
        public ActionResult Index(SearchViewModel s, string id)
        {
            bool showGrid = false;
            int _id = 0;

            GetPinnedItems();

            if (!string.IsNullOrWhiteSpace(Request.Url.Query) || !string.IsNullOrEmpty(id))
            {
                showGrid = true;

                if (!string.IsNullOrEmpty(id))
                {
                    try
                    {
                        if (int.TryParse(id, out _id) && _id > 0)
                        {
                            // We were passed a saved search id so fetch its details.
                            SearchOptions = _savedSearchService.GetSavedSearchOptions(_id, CurrentUser.SessionKey);

                            if (SearchOptions.Type == SearchType.Quick)
                            {
                                SearchOptionsQuick soq = (SearchOptionsQuick)SearchOptions;

                                s.SearchText = soq.SearchText;
                                s.SelectedId = soq.SelectedId;
                                s.SelectedRecordType = (int)soq.SelectedRecordType;
                                s.CountryID = (int)(soq.SearchAustralia ? Countries.Australia : soq.SearchNewZealand ? Countries.NewZealand : Countries.AllCountries);
                            }

                            s.Context = SearchOptions.Context;

                            s.Name = SearchOptions.SearchName;
                            s.SearchId = _id;
                        }
                        else if (Regex.IsMatch(id, @"^RS\d+"))
                        {
                            int recentSearchId = int.Parse(Regex.Match(id, @"\d+").Value);

                            SearchLogViewModel search = _searchService.GetRecentSearchById(recentSearchId, CurrentUser.SessionKey);

                            SearchOptions = GetSavedSearchOptions(search, s);
                        }
                    }
                    catch (Exception ex)
                    {
                        // Either the saved search doesnt exist or the user doesn't have access.
                        BasePage.LogException(ex, this.GetType().FullName, "Index", new NameValueCollection { { "id", _id.ToString() } });
                        ViewData["ErrorMessage"] = Search_InvalidSavedSearch;
                        return View(new SearchViewModel() { Pagination = new PaginationSearchViewModel() { Results = new List<SearchResult>() } });
                    }
                }
                else
                {
                    // Create a search object based on the SearchViewModel.
                    SearchOptions = (SearchOptionsQuick)GetSearchOptionsFromViewModel(s);
                }
            }
            else
            {
                if (SearchOptions == null)
                {
                    s.CountryID = CurrentUser.DefaultSearchCountry;
                }
            }

            // If we got search options then perform a search.
            if (SearchOptions != null && SearchOptions.HasSearchCriteria && !(SearchOptions is SearchOptionsAdvanced))
            {
                // This is a new search so clear the deleted and checkbox items of the previous search.
                ClearDeletedItems();
                ClearUnselectedItems();

                using (SearchServiceProxy searchServiceProxy = new SearchServiceProxy())
                {
                    s.Pagination.Results = searchServiceProxy.Search(SearchOptions, s.Pagination.SortColumn, s.Pagination.SortDirection, true, CurrentUser.UserID, 0, s.Pagination.PageSize,
                        PinnedItems, DeletedItems, UnselectedItems);

                    s.Pagination.ResultCount = searchServiceProxy.TotalResults();
                }

                // Calculate pagination.
                s.Pagination.CalculatePagination();

                // Check if all items in current search are pinned.
                s.Pagination.Pinning.AllPinned = PinnedItems.Count == s.Pagination.ResultCount;

                // Set current page to true for first load.
                s.Pagination.CurrentPageOnly = true;

                // Log search
                _searchService.LogSearch(new SearchLogViewModel()
                {
                    UserId = CurrentUser.UserID,
                    DebtorNumber = CurrentUser.DebtorNumber,
                    SearchType = (int)SearchOptions.Type,
                    SearchCriteria = SearchBAL.GetSearchCriteria(SearchOptions),
                    CreatedDate = DateTime.Now,
                    SavedSearchId = _id,
                    System = MediaContactsService.SystemType.Contacts,

Medianet.Contacts.Web/Medianet.Contacts.Web/Views/List/List.cshtml
@{
    ViewBag.Title = "List " + @Model.Name;
}
@using Medianet.Contacts.Web.Common
@model Medianet.Contacts.Web.ViewModels.List.ListViewModel

@section Javascript {
    @Scripts.Render("~/bundles/list")
}

@Html.Hidden("hdnListId", Model.ListId)
@Html.Hidden("hdnListSetId", Model.ListSet)
@Html.Hidden("hdnListIsPrivate", Model.IsPrivate.ToString())

<div class="d-flex align-items-center justify-content-between">
    <div class="col-12">
        <h2 class="mb-0">@Model.Name
            <button data-edit-list class="btn btn-link py-0 pr-0" data-toggle="tooltip" data-placement="right" title="Edit List"
                       data-edit-list-action="@Url.Action("Edit", "List", new { listId = Model.ListId })">
                <i class="fal fa-pencil" aria-hidden="true"></i>
            </button>
        </h2>
    </div>
</div>
<div class="row mt-3">
    <div class="col-12">
        <!-- The Living lists -->
        @if ((Model != null) && (Model.LivingList != null) && (Model.ListSet == 0))
        {
            @Html.Partial("_LivingListPartial", Model.LivingList)
        }
        @if ((Model != null) && (Model.ListResults != null))
        {
            @Html.Partial("_ListResultsPartial", Model.ListResults)
        }
        @if ((Model != null) && (Model.ListVersions != null))
        {
            @Html.Partial("_ListVersionPartial", Model.ListVersions)
        }
    </div>
</div>

Medianet.Contacts.Web/Medianet.Contacts.Web/Views/List/_AddListPartial.cshtml
@model Medianet.Contacts.Web.ViewModels.List.ListViewModel
<div class="modal-content">
    <form id="frmAddList" data-action="@Url.Action("Create", "List")" data-spinnercontainer="frmAddList">
        <div class="modal-header">
            <h4 class="modal-title">Save list</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <div class="form-row">
                <div class="col-12">
                    @Html.HiddenFor(m => Model.Type)
                    @Html.HiddenFor(m => Model.Expand)
                    @Html.HiddenFor(m => Model.CheckedItems)
                    @Html.HiddenFor(m => Model.CurrentPageOnly, new { id = "hfCurrentPageOnly" })
                    @Html.HiddenFor(m => Model.UncheckedItems, new { id = "hfUncheckedItems" })
                    @Html.HiddenFor(m => Model.CheckboxState, new { id = "hfCheckboxState" })
                    @Html.ValidationSummary(false, "", new { @class = " alert alert-danger d-none", id = "vsAddToList" })
                </div>
                <div class="col-12">
                    <input type="radio" value="New" name="GroupType" id="NewGroup" checked />
                    <label for="NewGroup" class="mr-3">New group</label>
                    <input type="radio" value="Existing" name="GroupType" id="ExistingGroup" />
                    <label class="ml-4" for="ExistingGroup">Existing group</label>
                </div>
                <div class="form-group col-12 select-container">
                    @Html.TextBoxFor(m => m.Group.Name, new { @class = "form-control", placeholder = "Group name", required = "required" })
                    @Html.ValidationMessageFor(m => m.Group.Name)
                    @Html.DropDownListFor(m => m.Group.Id, Model.Groups, new { @class = "form-control" })
                </div>                
                <div class="col-12 mt-2">
                    <input type="radio" value="New" name="ListType" id="NewList" checked />
                    <label for="NewList" class="mr-3">New list</label>
                    <input type="radio" value="Existing" name="ListType" id="ExistingList" data-action="@Url.Action("GetLists", "List")" />
                    <label class="ml-4" for="ExistingList">Existing list</label>
                </div>
                <div class="form-group col-12 select-container">
                    @Html.TextBoxFor(m => m.Name, new { @class = "form-control", placeholder = "List name", required = "required" })
                    @Html.ValidationMessageFor(m => m.Name)
                    <span id="GroupListContainer"></span>
                </div>
                <div class="form-group col-12">
                    <input type="radio" value="false" name="isPrivate" id="Public" @(!Model.IsPrivate ? "checked" : "") />
                    <label for="Public" class="mr-3">Public</label>
                    <input type="radio" value="true" name="isPrivate" id="Private" @(Model.IsPrivate ? "checked" : "") />
                    <label class="ml-4" for="Private">Private</label>
                    <span data-toggle="tooltip" data-placement="right" class="tooltip-muted"
                          title="Public indicates that all users at your company will be able to view and edit this list. Private indicates that this list can only be viewed and edited by you.">
                        <i class="fa fa-info-circle"></i>
                    </span>
                </div>
                
            </div>
        </div>
        <div class="modal-footer justify-content-center">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
            <button type="submit" class="btn btn-primary px-4" data-spinnercontainer="btnAddList">Save</button>
        </div>
    </form>
</div>

Medianet.Contacts.Web/Medianet.Contacts.Web/Views/List/_EditListPartial.cshtml
@using Medianet.Contacts.Web.Common

@model Medianet.Contacts.Web.ViewModels.List.ListViewModel

@{
   var disableIsPrivate =  Model.UserId != SessionManager.Instance.CurrentUser.UserID;
}

<div class="modal-content">
    @using (Html.BeginForm("Edit", "List", FormMethod.Post, new { id = "frmEdit" }))
    {
        <div class="modal-header">
            <h4 class="modal-title">Edit list</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <div class="form-row">
                <div class="col-12">
                    @Html.HiddenFor(m => m.ListId)
                    @Html.ValidationSummary(false, "", new { @class = " alert alert-danger d-none", id = "vsEdit" })
                </div>


                <div class="form-group col-12 mt-2">
                    @Html.TextBoxFor(m => m.Name, new { @class = "form-control", placeholder = "List name", required = "required" })
                    @Html.ValidationMessageFor(m => m.Name)
                </div>
                <div class="form-group col-12">
                    <input type="radio" value="false" name="isPrivate" disabled="@disableIsPrivate" id="Public" @(Model.IsPrivate ? "" : "checked='checked'" ) />
                    <label for="Public">&nbsp;Public</label>
                    <input type="radio" value="true" name="isPrivate" disabled="@disableIsPrivate" id="Private" @(Model.IsPrivate ? "checked='checked'" : "" ) />
                    <label class="ml-4" for="Private">&nbsp;Private</label>
                    <span class="tooltip-muted" data-toggle="tooltip" data-placement="right" title="Public indicates that all users at your company will be able to view and edit this list. Private indicates that this list can only be viewed and edited by you.">
                        <i class="fa fa-info-circle"></i>
                    </span>
                </div>
            </div>
        </div>
        <div class="modal-footer justify-content-center">
            <button type="button" class="btn btn-secondary" id="cancel-button" data-dismiss="modal">Cancel</button>
            <button type="submit" class="btn btn-primary px-4" data-spinnercontainer="btnSave">Save</button>
        </div>
    }
</div>

Medianet.Contacts.Web/Medianet.Contacts.Web/Views/List/_ListPagePartial.cshtml
@model Medianet.Contacts.Web.ViewModels.List.ListResultsViewModel

@{ Html.RenderPartial("_ListResultsCountPartial", Model); }

@{ Html.RenderPartial("_PaginationPartial", Model); }

<table id="rows">
    <tbody>
        @if (Model != null && Model.Pagination.Results != null)
        {
            Html.RenderPartial("_ListResultsRowPartial", Model);
        }
    </tbody>
</table>

Medianet.Contacts.Web/Medianet.Contacts.Web/Views/List/_ListPartial.cshtml
@using System.Collections.Generic
@using System.Linq

@if (ViewData["Lists"] != null) {
    @Html.DropDownList("ListId", (IEnumerable<SelectListItem>)ViewData["Lists"], new { @class = "form-control" })
}

Medianet.Contacts.Web/Medianet.Contacts.Web/Views/List/_ListResultsRowPartial.cshtml
@using Medianet.Contacts.Wcf.DataContracts.DTO;

@model Medianet.Contacts.Web.ViewModels.List.ListResultsViewModel

@foreach (var item in Model.Pagination.Results)
{
    <tr @(item.IsEntityDeleted ? "class=pinned" : "")>
        <td scope="row">
            @if (Model.Pagination.ListSet == 0)
            {
                <input type="checkbox" name="checkbox-outlet" title="Select" @(item.Selected ? "checked=\"checked\"" : "") id="@item.ToClientString()" data-record="@item.ToClientString()" data-record-id="@item.RecordId.ToString()">
            }

            <label for="@(Model.Pagination.ListSet == 0 ? item.ToClientString() : "")">
                @Html.PrivateIconHelper(item.OutletType)
                @if (@item.IsGeneric)
                {
                    @Html.Label(item.OutletName, new {@class = "rtbOutlet" + (item.HasPrivateOutlet ? " rtbPrivate" : "")})
                }
                else
                {
                    if (!string.IsNullOrWhiteSpace(@item.OutletID) && !item.OutletID.Equals("0"))
                    {

                        <a href="@Url.Action("Index", "Outlet", new { Id = (item.OutletID ?? string.Empty).Trim(), recordType = (int) item.OutletType })"
                            class="rtbOutlet@(item.HasPrivateOutlet ? " rtbPrivate" : "")"
                            data-toggle="popover" data-html="true"
                            data-outletId="@item.OutletID" data-recordType="@(Convert.ToInt32(item.OutletType))"
                            data-action="@(Url.Action("OutletPreview", "Outlet"))"><b>@item.OutletName</b></a>
                    }
                }
    
            </label>
        </td>
        <td>
            @if (!string.IsNullOrWhiteSpace(item.ContactIds) && !item.ContactIds.Equals("0"))
            {
                if (item.ContactIds.Contains('#'))
                {
                    <a href="@Url.Action("Expand","Search", new
                            {
                                outletid = item.OutletID,
                                type = (int)item.Type,
                                Advanced = false
                            
                            })">
                        <span data-toggle="tooltip" data-placement="right" title="@item.FullName"><b>@item.ContactDisplay</b></span>
                    </a>
                }
                else
                {
                    @Html.PrivateIconHelper(item.ContactType)
                    <a href="@Url.Action("Index", "Contact", new { outletId = (item.OutletID ?? string.Empty).Trim(), contactId = (item.ContactIds ?? string.Empty).Trim() , recordType = (int)item.ContactType })"
                       class="rtbName@(item.HasPrivateContact ? " rtbPrivate" : "")"
                       data-toggle="popover" data-html="true"
                       data-contactId="@item.ContactIds" data-outletId="@item.OutletID" data-recordType="@(Convert.ToInt32(item.ContactType))"
                       data-action="@(Url.Action("ContactPreview","Contact"))"><b>@item.ContactDisplay</b></a>
                }
            }
            @Html.Hidden(item.ContactId)
        </td>
        <td>@item.JobTitle</td>
        <td>
            <span data-toggle="tooltip" data-placement="left" title="@item.SubjectName">@item.SubjectDisplay</span>
        </td>
        <td>@item.ProductTypeName</td>
        <td>@item.MediaInfluencerScore</td>
        <td>@item.CityName</td>
        @if (Model.Pagination.ListSet == 0)
        {
            <td class="text-right actionBtns">
                <button class="btn btn-sm btn-link pl-0 btnDelete" data-confirm="Delete record" data-confirm-text="the selected record" data-toggle="tooltip" data-placement="left" title="Delete"><i class="fal fa-fw fa-times"></i></button>
            </td>
        }
    </tr>
}