Medianet.Contacts.Web/Medianet.Contacts.Web/ViewModels/Distribution/DistributionViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using Medianet.Contacts.Web.Common.Model;

namespace Medianet.Contacts.Web.ViewModels.Distribution
{
    public class DistributionViewModel
    {
        [Required]
        [Display(Name = "Company Name")]
        public string CompanyName { get; set; }
        [Required]
        [Display(Name = "Customer Id")]
        public string DebtorNumber { get; set; }
        public string SenderName { get; set; }
        [Required]
        [Display(Name = "Work Phone Number")]
        public string WorkPhoneNumber { get; set; }
        [Required]
        [Display(Name = "Email Address")]
        public string EmailAddress { get; set; }
        public string AfterHoursNumber { get; set; }
        public string CustomerReference { get; set; }
        public string SelectedLists { get; set; }
        public List<int> SelectedListIds { get; set; }
        public bool DistributionWire { get; set; }

        public bool WireAll { get; set; }
        public bool WireTas { get; set; }
        public bool WireVic { get; set; }
        public bool WireNsw { get; set; }
        public bool WireAct { get; set; }
        public bool WireSa { get; set; }
        public bool WireWa { get; set; }
        public bool WireQld { get; set; }
        public bool WireNt { get; set; }

        public bool OnHold { get; set; }
        public string HoldTime { get; set; }
        public string SpecialInstructions { get; set; }
        public HttpPostedFileBase Release { get; set; }
        public HttpPostedFileBase Attachment { get; set; }
        public int ReleaseId { get; set; }
    }
}

Medianet.Contacts.Web/Medianet.Contacts.Web/Controllers/DistributionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Medianet.Contacts.Web.Common;
using Medianet.Contacts.Web.Common.BO;
using Medianet.Contacts.Web.Common.Model;
using Medianet.Contacts.Web.Common.Util;
using Medianet.Contacts.Web.Filters;
using Medianet.Contacts.Web.Services.Distribution;
using Medianet.Contacts.Web.Services.List;
using Medianet.Contacts.Web.ViewModels.Distribution;
using Medianet.Contacts.Web.ViewModels.List;
using System.Configuration;

namespace Medianet.Contacts.Web.Controllers
{
    public class DistributionController : BaseController
    {
        private IListService _listService;
        private IDistributionService _distributionService;
        private List<ListViewModel> _lists = null;

        public DistributionController() : base()
        {
            _listService = ListService.CreateListService();
            _distributionService = DistributionService.Create();
        }

        protected override void Dispose(bool disposing)
        {
            _listService?.Dispose();
            _distributionService?.Dispose();
            base.Dispose(disposing);
        }

        [HttpGet]
        [HandleHtmlError, HandleAuthentication]
        public ActionResult Index(int? listId)
        {
            var model = InitialiseModel();
            var selectedLists = new List<int>();

            if (listId.HasValue)
                selectedLists.Add(listId.Value);

            PopulateLists(selectedLists);

            return View(model);
        }

        [HttpPost]
        [HandleHtmlError, HandleAuthentication]
        public ActionResult Index(DistributionViewModel model)
        {
            ValidateDistribution(model);

            PopulateLists(model.SelectedListIds);

            if (ModelState.IsValid)
            {
                var releaseId = Submit(model);

                // Clear the form and return the release id of the release just created
                model = InitialiseModel();
                model.ReleaseId = releaseId;
                ViewBag._selectedLists = null;
                ModelState.Clear();

                return View(model);
            }

            return View(model);
        }

        private DistributionViewModel InitialiseModel()
        {
            var model = new DistributionViewModel();

            model.CompanyName = CurrentUser.CompanyName;
            model.DebtorNumber = CurrentUser.DebtorNumber;
            model.SenderName = CurrentUser.FullName;
            model.EmailAddress = CurrentUser.EmailAddress;
            model.SelectedLists = string.Empty;
            model.DistributionWire = false;
            model.WireAll = true;
            model.WireTas = true;
            model.WireVic = true;
            model.WireNsw = true;
            model.WireAct = true;
            model.WireSa = true;
            model.WireWa = true;
            model.WireQld = true;
            model.WireNt = true;
            model.OnHold = false;
            model.SpecialInstructions = string.Empty;
            model.ReleaseId = 0;

            return model;
        }

        private List<ListViewModel> Lists
        {
            get
            {
                if (_lists == null)
                    _lists = _listService.GetLists(CurrentUser.UserID, CurrentUser.SessionKey);

                return _lists;
            }
        }

        private void PopulateLists(List<int> selectedLists)
        {
            var baseLists = new List<ListBase>();
            var baseSelectedLists = new List<ListBase>();

            baseLists.AddRange(
                Lists.Select(lst => new List { Id = lst.ListId, Name = lst.Name }).OrderBy(l => l.Name).ToList());

            if (selectedLists != null)
            {
                foreach (var id in selectedLists)
                {
                    var selectedList = baseLists.FirstOrDefault(l => l.Id == id);
                    if (selectedList != null)
                        baseSelectedLists.Add(selectedList);
                }
            }

            ViewBag._lists = baseLists;
            ViewBag._selectedLists = baseSelectedLists;

        }

        private void ValidateDistribution(DistributionViewModel model)
        {
            if (model.Release == null || model.Release.ContentLength == 0)
            {
                ModelState.AddModelError("Release", "Please attach a release document.");
            }

            if (model.DistributionWire)
            {
                if (!model.WireAll && !model.WireTas && !model.WireVic && !model.WireNsw && !model.WireAct &&
                    !model.WireSa && !model.WireWa && !model.WireQld && !model.WireNt)
                {
                    ModelState.AddModelError("DistributionWire", "Please select at least one of the wire states.");
                }
            }

            if (string.IsNullOrEmpty(model.SelectedLists))
            {
                ModelState.AddModelError("SelectedLists", "Please select one or more lists to distribute to.");
            }

            model.SelectedListIds = string.IsNullOrWhiteSpace(model.SelectedLists) ? new List<int>() : model.SelectedLists.ParseIntCSV();
        }

        private int Submit(DistributionViewModel model)
        {
            int releaseId = 0;
            Stream headerStream = null;
            Stream emailCsvStream = null;
            Stream emailTextStream = null;

            try
            {
                DataSet dsEmail;

                // Get the details of the distribution.
                Distribute distribute = GetDistribution(model);

                // Create the Job on the database.
                releaseId = _distributionService.CreateJob(distribute);

                dsEmail = _distributionService.GetEmailFax(model.SelectedLists);

                // Create the Header file.
                headerStream = CreateHeaderFile(releaseId, model, distribute, dsEmail.Tables[0].Rows.Count);

                emailCsvStream = CreateCsvStream(dsEmail.Tables[0]);
                emailTextStream = CreateTextStream(dsEmail.Tables[0]);

                // Send all the content to CS staff in an email.
                EmailContactUs emailContact = new EmailContactUs();

                emailContact.SendEmail_Distribution(
                                releaseId.ToString(),
                                ConfigurationManager.AppSettings["ClientServiceEmail"],
                                ConfigurationManager.AppSettings["ClientServiceEmail"],
                                "Medianet Contacts Database Distribution",
                                headerStream, emailCsvStream, emailTextStream,
                                model.Release?.InputStream, model.Release?.FileName,
                                model.Attachment?.InputStream, model.Attachment?.FileName,
                                "Find attached distribution files.",
                                model.SenderName.Trim(), model.EmailAddress.Trim());
            }
            finally
            {
                headerStream?.Close();
                emailCsvStream?.Close();
                emailTextStream?.Close();
            }

            return releaseId;
        }

        /// <summary>
        /// Method for creating header file as attachment
        /// </summary>
        private Stream CreateHeaderFile(int jobId, DistributionViewModel model, Distribute dist, int emailCount)
        {
            var ms = new MemoryStream();
            string aapNewswire = "";
            string distributionList = "";

            // Check if they also want Wire.
            if (model.DistributionWire)
            {
                if (model.WireAll)
                    aapNewswire = AppendToString("ALL", aapNewswire);
                if (model.WireTas)
                    aapNewswire = AppendToString("TAS", aapNewswire);
                if (model.WireVic)
                    aapNewswire = AppendToString("VIC", aapNewswire);
                if (model.WireNsw)
                    aapNewswire = AppendToString("NSW", aapNewswire);
                if (model.WireAct)
                    aapNewswire = AppendToString("ACT", aapNewswire);
                if (model.WireSa)
                    aapNewswire = AppendToString("SA", aapNewswire);
                if (model.WireWa)
                    aapNewswire = AppendToString("WA", aapNewswire);
                if (model.WireQld)
                    aapNewswire = AppendToString("QLD", aapNewswire);
                if (model.WireNt)
                    aapNewswire = AppendToString("NT", aapNewswire);
            }

            foreach (int id in model.SelectedListIds)
            {
                var selectedList = Lists.FirstOrDefault(l => l.ListId == id);
                if (selectedList != null)
                    distributionList = AppendToString(selectedList.Name, distributionList);
            }

            using (StreamWriter sw = new StreamWriter(ms, Encoding.UTF8, 1024, true))
            {
                sw.WriteLine("Job No: " + jobId.ToString());
                sw.WriteLine("Organisation Name: " + model.CompanyName);
                sw.WriteLine("Customer ID Number: " + CurrentUser.DebtorNumber);
                sw.WriteLine("Sender Name: " + model.SenderName);
                sw.WriteLine("Sender Phone: " + model.WorkPhoneNumber);
                sw.WriteLine("Sender Mobile Phone / After Hours number: " + model.AfterHoursNumber);
                sw.WriteLine("Sender E-mail Address: " + model.EmailAddress);
                sw.WriteLine("Client Reference Number: " + model.CustomerReference);
                sw.WriteLine("Distribution List Name:" + distributionList);
                sw.WriteLine("Release File: " + model.Release.FileName);

                if (model.Attachment != null)

Medianet.Contacts.Web/Medianet.Contacts.Web/Views/Distribution/Index.cshtml
@model Medianet.Contacts.Web.ViewModels.Distribution.DistributionViewModel
@{
    ViewBag.Title = "Send media release";
}
@section Styles {
    @Styles.Render("~/Content/distribution")
}
@section Javascript {
    @Scripts.Render("~/bundles/distribution")
    <script type="text/javascript">
        var _lists = @Html.Raw(Json.Encode(@ViewBag._lists));
        var _selectedLists = @Html.Raw(Json.Encode(@ViewBag._selectedLists));
    </script>
}

@using (Html.BeginForm("Index", "Distribution", FormMethod.Post, new { id = "distributionForm", encType = "multipart/form-data" }))
{
    @Html.HiddenFor(m => m.ReleaseId)

    <div class="d-flex align-items-end justify-content-between">
        <h2 class="mb-0">Send Media Release</h2>
    </div>

    <div class="card mt-3 mb-4 mb-xl-5">
        <div class="card-body">
            <div class="row">
                <div class="col-12 col-lg-10 offset-lg-1">                    
                    <div class="mt-4">
                        <h3>Enter job information</h3>
                        <div class="form-row">
                            <div class="form-group col-md-6 col-lg-4">
                                @Html.TextBoxFor(m => m.CompanyName, new { placeholder = "Company name", @readonly = "readonly", @class = "form-control" })
                                @Html.ValidationMessageFor(m => m.CompanyName)
                            </div>
                            <div class="form-group col-md-6 col-lg-4">
                                @Html.TextBoxFor(m => m.DebtorNumber, new { placeholder = "Customer Id", @readonly = "readonly", @class = "form-control" })
                                @Html.ValidationMessageFor(m => m.DebtorNumber)
                            </div>
                            <div class="form-group col-md-6 col-lg-4">
                                @Html.TextBoxFor(m => m.SenderName, new { placeholder = "Sender name", @class = "form-control" })
                            </div>
                            <div class="form-group col-md-6 col-lg-4">
                                @Html.TextBoxFor(m => m.WorkPhoneNumber, new { placeholder = "Work phone", @class = "form-control" })
                                @Html.ValidationMessageFor(m => m.WorkPhoneNumber)
                            </div>
                            <div class="form-group col-md-6 col-lg-4">
                                @Html.TextBoxFor(m => m.EmailAddress, new { placeholder = "Email address", @class = "form-control" })
                                @Html.ValidationMessageFor(m => m.EmailAddress)
                            </div>
                            <div class="form-group col-md-6 col-lg-4">
                                @Html.TextBoxFor(m => m.AfterHoursNumber, new { placeholder = "Mobile phone / After hours number", @class = "form-control" })
                            </div>
                            <div class="form-group col-md-6 col-lg-4">
                                @Html.TextBoxFor(m => m.CustomerReference, new { placeholder = "Customer reference", @class = "form-control" })
                            </div>
                            <div class="form-group col-md-6 col-lg-4">
                                <div class="searchInput">
                                    @Html.TextBoxFor(m => m.SelectedLists, new { id = "SelectedLists", @class = "hidden" })
                                </div>
                                <span class="tokenInput-btn-container">
                                    <i class="fa fa-caret-down"></i>
                                    <input type="button" class="dropdown btnShowAll" name="showAll" title="Show all" tabindex="-1">
                                    @Html.ValidationMessageFor(m => m.SelectedLists)
                                </span>
                            </div>
                        </div>

                        <h5 class="mt-3 mb-1">Attach release document</h5>
                        <div class="form-row">
                            <div class="form-group col-md-6 col-lg-4">
                                <div class="custom-file">
                                    <input type="file" class="custom-file-input" id="Release" name="Release">
                                    <label class="custom-file-label text-nowrap text-truncate" for="Release">Choose file</label>
                                </div>
                                @Html.ValidationMessageFor(m => m.Release)
                            </div>
                        </div>                        
                    </div>
                    
                    <div class="mt-4">
                        <h3>Select distribution method</h3>
                        <p>To support your distribution to your targeted Medianet Contacts, you can choose to include distribution to one of Medianet's expertly prepared media lists or include newswire distributions to fortify your reach to major newsrooms across Australia.</p>
                        <div class="form-row">
                            <div class="col-12">
                                <div class="form-group">
                                    @Html.CheckBox("DistributionEmail", true, new { @disabled = "disabled" })
                                    <label for="DistributionEmail">Email</label>
                                </div>
                                <div class="form-group">
                                    @Html.CheckBoxFor(m => m.DistributionWire, null)
                                    <label for="DistributionWire">Newswire feeds</label>
                                    @Html.ValidationMessageFor(m => m.DistributionWire)
                                </div>
                                <div class="form-check form-check-inline wireDist">
                                    <div class="form-group mr-4">
                                        @Html.CheckBoxFor(m => m.WireAll)
                                        <label for="WireAll">ALL</label>
                                    </div>
                                    <div class="form-group mr-4">
                                        @Html.CheckBoxFor(m => m.WireTas)
                                        <label for="WireTas">TAS</label>
                                    </div>
                                    <div class="form-group mr-4">
                                        @Html.CheckBoxFor(m => m.WireVic)
                                        <label for="WireVic">VIC</label>
                                    </div>
                                    <div class="form-group mr-4">
                                        @Html.CheckBoxFor(m => m.WireNsw)
                                        <label for="WireNsw">NSW</label>
                                    </div>
                                    <div class="form-group mr-4">
                                        @Html.CheckBoxFor(m => m.WireAct)
                                        <label for="WireAct">ACT</label>
                                    </div>
                                    <div class="form-group mr-4">
                                        @Html.CheckBoxFor(m => m.WireSa)
                                        <label for="WireSa">SA</label>
                                    </div>
                                    <div class="form-group mr-4">
                                        @Html.CheckBoxFor(m => m.WireWa)
                                        <label for="WireWa">WA</label>
                                    </div>
                                    <div class="form-group mr-4">
                                        @Html.CheckBoxFor(m => m.WireQld)
                                        <label for="WireQld">QLD</label>
                                    </div>
                                    <div class="form-group">
                                        @Html.CheckBoxFor(m => m.WireNt)
                                        <label for="WireNt">NT</label>
                                    </div>
                                </div>
                            </div>
                        </div>                       
                    </div>
                    <div class="mt-4">
                        <h3>Attach additional documents</h3>
                        <div class="form-row">
                            <div class="col-12">
                                <p>Attach additional documents such as an image, audio file or PDF.</p>
                            </div>
                            <div class="form-group col-md-6 col-lg-4">
                                <div class="custom-file">
                                    <input type="file" class="custom-file-input" id="Attachment" name="Attachment">
                                    <label class="custom-file-label" for="Attachment">Choose file</label>
                                </div>
                                <span class="form-text text-muted">Maximum file size: 2 MB</span>
                            </div>
                        </div> 
                    </div>
                    <div class="mt-4">
                        <h3>Submit for distribution</h3>
                        <p>Please contact your Account Manager or Client Services for pricing on sending a media release. Costs for distribution are based on your list and wire selections and any associated attachments.</p>
                        <div class="form-row">
                            <div class="col-md-6 col-lg-4">
                                <div class="form-group">
                                    <input type="radio" name="OnHold" @(!Model.OnHold ? "checked=\"checked\"" : "")
                                           id="OnHold_false" value="false" />
                                    <label for="OnHold_false">Immediate</label>
                                </div>
                                <div class="form-group">
                                    <input type="radio" name="OnHold" @(Model.OnHold ? "checked=\"checked\"" : "")
                                           id="OnHold_true" value="true" />
                                    <label for="OnHold_true">Hold</label>

                                    <div class="form-group holdCalendar">
                                        <div class="input-group mb-3">
                                            @Html.TextBoxFor(m => m.HoldTime, new { placeholder = "Select hold date/time", @class = "form-control" })
                                            <div class="input-group-append calendarButton cursor-pointer">
                                                <span class="input-group-text"><i class="fal fa-calendar-alt"></i></span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>                           
                        
                            <div class="form-group col-md-12 mt-4">
                                @Html.TextAreaFor(m => m.SpecialInstructions, new { placeholder = "Special instructions", @class = "form-control", autocomplete = "off" })
                            </div>
                        
                            <div class="form-group col-md-12 mt-5 text-right">
                                <button type="submit" class="btn btn-primary px-5 py-2" tabindex="" form="distributionForm" value="Submit">Submit</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}