Medianet.Contacts.Web/Medianet.Contacts.Web/ViewModels/AllLists/AllListsViewModel.cs
using System;
using Medianet.Contacts.Wcf.DataContracts.DTO;
using System.Collections.Generic;

namespace Medianet.Contacts.Web.ViewModels.AllLists
{
    public class ListsGroupedViewModel : PaginationGenericViewModel
    {
        public List<ListViewModel> Lists { get; set; }
        public int GroupId { get; set; }
        public AllListsSortColumn AllListsSortColumn { get; set; }

    }

    public class ListViewModel
    {
        public int ListId { get; set; }

        public string ListName { get; set; }

        public int GroupId { get; set; }

        public string GroupName { get; set; }

        public string Visibility { get; set; }

        public DateTime CreatedDate { get; set; }

        public int UserId { get; set; }

        public string UserFullName { get; set; }
    } 
}

Medianet.Contacts.Web/Medianet.Contacts.Web/ViewModels/AllLists/DeleteListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Medianet.Contacts.Web.ViewModels.AllLists
{
    public class DeleteListViewModel
    {
        public int ListId { get; set; }
        public string ListName { get; set; }
    }
}

Medianet.Contacts.Web/Medianet.Contacts.Web/ViewModels/AllLists/RebindGroupViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Medianet.Contacts.Wcf.DataContracts.DTO;

namespace Medianet.Contacts.Web.ViewModels.AllLists
{
    public class RebindGroupViewModel
    {
        public int GroupId { get; set; }
        public AllListsSortColumn SortColumn { get; set; }
        public SortDirection SortDirection { get; set; }
       
    }
}

Medianet.Contacts.Web/Medianet.Contacts.Web/ViewModels/AllLists/RenameGroupViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Medianet.Contacts.Web.ViewModels.AllLists
{
    public class RenameGroupViewModel
    {
        public int GroupId { get; set; }
        public string GroupName { get; set; }
        [Display(Name = "New Group Name")]
        [Required]
        public string NewGroupName { get; set; }
    }
}

Medianet.Contacts.Web/Medianet.Contacts.Web/Controllers/AllListsController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using Medianet.Contacts.Web.Services;
using Medianet.Contacts.Web.ViewModels.AllLists;
using Medianet.Contacts.Web.Filters;
using System.Web.UI;
using Medianet.Contacts.Wcf.DataContracts.DTO;
using System.Linq;
using Medianet.Contacts.Web.Services.List;
using System.Net;

namespace Medianet.Contacts.Web.Controllers
{
    public class AllListsController : BaseController
    {
        #region Field

        private IGroupListService _groupListService;
        private IListService _listService;

        #endregion

        public AllListsController() : base()
        {
            _groupListService = GroupListService.CreateGroupListService();
            _listService = ListService.CreateListService();
        }

        protected override void Dispose(bool disposing)
        {
            _groupListService?.Dispose();
            _listService?.Dispose();
            base.Dispose(disposing);
        }

        #region Display List

        // GET: /AllLists/
        [HttpGet]
        [HandleHtmlError, HandleAuthentication]
        public ActionResult Index()
        {
            List<ListsGroupedViewModel> listGrouped = _groupListService.GetGroupedListsDebtorUserId(CurrentUser.UserID, CurrentUser.DebtorNumber);
            return View(listGrouped);
        }

        [HttpGet]
        [HandleAjaxAuthorization, HandleAjaxError]
        public PartialViewResult RebindAll()
        {
            List<ListsGroupedViewModel> listGrouped = _groupListService.GetGroupedListsDebtorUserId(CurrentUser.UserID, CurrentUser.DebtorNumber);
            return PartialView("_AllGroupedListsPartial", listGrouped);
        }

        [HttpPost]
        [OutputCache(Location = OutputCacheLocation.None)]
        [HandleAjaxAuthorization, HandleAjaxError]
        public PartialViewResult RebindGroup(RebindGroupViewModel model)
        {
            List<ListViewModel> listGrouped = _groupListService.GetGroupedListsDebtorUserIdGroupId(model.GroupId,
                CurrentUser.UserID, CurrentUser.DebtorNumber);

            ListsGroupedViewModel orderedGroup = new ListsGroupedViewModel()
            {
                GroupId = model.GroupId
            };

            if (listGrouped != null)
            {
                switch (model.SortColumn)
                {
                    case AllListsSortColumn.ListName:
                        orderedGroup.Lists = model.SortDirection == SortDirection.ASC ? listGrouped.OrderBy(o => o.ListName).ToList() : listGrouped.OrderByDescending(o => o.ListName).ToList();
                        break;
                    case AllListsSortColumn.UserFullName:
                        orderedGroup.Lists = model.SortDirection == SortDirection.ASC ? listGrouped.OrderBy(o => o.UserFullName).ToList() : listGrouped.OrderByDescending(o => o.UserFullName).ToList();
                        break;
                    case AllListsSortColumn.CreatedDate:
                        orderedGroup.Lists = model.SortDirection == SortDirection.ASC ? listGrouped.OrderBy(o => o.CreatedDate).ToList() : listGrouped.OrderByDescending(o => o.CreatedDate).ToList();
                        break;
                    case AllListsSortColumn.Default:
                        orderedGroup.Lists = model.SortDirection == SortDirection.ASC ? listGrouped.OrderBy(o => o.ListName).ToList() : listGrouped.OrderByDescending(o => o.ListName).ToList();
                        break;

                }
            }
            return PartialView("_ListsPartial", orderedGroup);

        }

        [HttpPost]
        [HandleAjaxAuthorization, HandleAjaxError]
        public ActionResult DeleteList(int listId) {

            _groupListService.DeleteOnListIdAndUserId(CurrentUser.UserID, listId);

            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }

        #endregion
    }
}

Medianet.Contacts.Web/Medianet.Contacts.Web/Controllers/GroupController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using System.Web.UI;
using Medianet.Contacts.Wcf.DataContracts.DTO;
using Medianet.Contacts.Web.Filters;
using Medianet.Contacts.Web.ViewModels;
using Medianet.Contacts.Web.Services;
using System.Net;
using Medianet.Contacts.Web.ViewModels.AllLists;
using Medianet.Contacts.Web.Services.Search;
using System;

namespace Medianet.Contacts.Web.Controllers
{
    public class GroupController : BaseController
    {
        private IGroupService _groupService;
        private IGroupListService _groupListService;
        private ISavedSearchService _savedSearchService;
        public GroupController() {
            _groupService = GroupService.CreateGroupService();
            _savedSearchService = SavedSearchService.CreateSavedSearchService();
            _groupListService = GroupListService.CreateGroupListService();
        }

        protected override void Dispose(bool disposing) {
            if (_groupService != null) _groupService.Dispose();
            if (_groupListService != null) _groupListService.Dispose();
            if (_savedSearchService != null) _savedSearchService.Dispose();
            base.Dispose(disposing);
        }

        [OutputCache(Location = OutputCacheLocation.None)]
        [HandleAjaxAuthorization, HandleAjaxError]
        public JsonResult Rename(int id, string name)
        {
            return Json(new { result = _groupService.RenameGroup(id, name) });
        }

        [HttpGet]
        [OutputCache(Location = OutputCacheLocation.None)]
        [HandleAjaxAuthorization, HandleAjaxError]
        public ActionResult Tasks()
        {
            return PartialView("_GroupListPartial", GetGroups(GroupType.Task));
        }

        [HttpGet]
        [OutputCache(Location = OutputCacheLocation.None)]
        [HandleAjaxAuthorization, HandleAjaxError]
        public ActionResult Searches()
        {
            return PartialView("_GroupListPartial", GetGroups(GroupType.Search));
        }

        [HttpGet]
        [OutputCache(Location = OutputCacheLocation.None)]
        [HandleAjaxAuthorization, HandleAjaxError]
        public ActionResult Lists()
        {
            return PartialView("_GroupListPartial", GetGroups(GroupType.List));
        }

        [HttpGet]
        [HandleAjaxAuthorization, HandleAjaxError]
        public PartialViewResult RenameGroupModal(int groupId)
        {
            var results = _groupService.GetGroupById(groupId, CurrentUser.UserID);

            return PartialView("_RenameGroup",
                new RenameGroupViewModel() { GroupId = results.Id, GroupName = results.Name });
        }

        [HttpPost]
        [HandleAjaxAuthorization, HandleAjaxError]
        public ActionResult RenameGroup(RenameGroupViewModel model)
        {
            _groupService.RenameGroup(model.GroupId, model.NewGroupName);

            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }

        [HttpPost]
        [HandleAjaxAuthorization, HandleAjaxError]
        public ActionResult DeleteGroupList(int groupId)
        {
            _groupListService.DeleteGroupList(groupId, CurrentUser.UserID);

             return new HttpStatusCodeResult(HttpStatusCode.OK);
        }

        [HttpPost]
        [HandleAjaxAuthorization, HandleAjaxError]
        public ActionResult DeleteGroupSearch(int groupId)
        {
            _savedSearchService.DeleteGroupSearch(groupId, CurrentUser.UserID);

            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }
        
        private List<GroupViewModel> GetGroups(GroupType type) {
            var groups = _groupService.GetGroupsByType(type, CurrentUser.UserID, CurrentUser.SessionKey);

            if (groups != null && groups.Count == 0)
                HttpContext.Response.StatusCode = 404;

            return groups;
        }
    }
}

Medianet.Contacts.Web/Medianet.Contacts.Web/Views/AllLists/Index.cshtml
@{
    ViewBag.Title = "Lists";
}
@section Javascript {
    @Scripts.Render("~/bundles/alllists")
}

<div class="d-flex align-items-center justify-content-between">
    <div>
        <h2 class="mb-0 text-nowrap">Lists</h2>
    </div>
</div>
<div class="card mt-3 mb-4 mb-xl-5">
    <div class="card-body">
        <div class="row">
            @if (Model == null)
            {
                <div class="col">
                    <h4 class="mb-3">You currently don't have any saved lists.</h4>
                    <p>Once you save a list, you will be able to view the list here.</p>
                </div>
            }
            else
            {
                <div class="col-12 col-lg-10 offset-lg-1">
                    <h4>Saved lists</h4>
                    <div class="groupedListsPartial">
                        @{ Html.RenderPartial("_AllGroupedListsPartial"); }
                    </div>                
                </div>
            }
        </div>
    </div>
</div>

Medianet.Contacts.Web/Medianet.Contacts.Web/Views/AllLists/_AllGroupedListsPartial.cshtml
@using Medianet.Contacts.Web.Common.Util
@using System.Collections.Generic
@using System.Linq
@using Medianet.Contacts.Wcf.DataContracts.DTO;

@model List<Medianet.Contacts.Web.ViewModels.AllLists.ListsGroupedViewModel>

@if (Model != null)
{
    foreach (var group in Model)
    {
        var groupName = @group.Lists.Select(g => g.GroupName).First();
        var groupId = @group.Lists.Select(g => g.GroupId).First();
        <div class="group" data-group="@groupId">
            <div class="group-header collapsible">
                <h5 class="d-flex align-items-center mb-0">
                    <span class="collapsed cursor-pointer" data-toggle="collapse" data-target="#grp_@groupId">
                        <i class="fal fa-chevron-down fa-fw" aria-hidden="true"></i>
                        <span class="pl-1" data-group-name-id="@groupId">@groupName</span>
                    </span>
                    <span class="actionBtns ml-auto">
                        <button data-rename-group class="btn btn-sm btn-link py-0" title="Rename" data-group-id="@groupId"
                                data-rename-group-action="@Url.Action("RenameGroupModal", "Group", new { groupId = @groupId })">
                            <i class="fal fa-pencil" aria-hidden="true"></i>
                        </button>
                        <button data-delete-group class="btn btn-sm btn-link py-0" data-id="@groupId" data-confirm="Delete group list" data-confirm-text="@groupName" data-action="@Url.Action("DeleteGroupList", "Group")">
                            <i class="fal fa-times" aria-hidden="true"></i>
                        </button>
                    </span>
                </h5>
            </div>
            <div class="collapse" id="grp_@groupId" data-spinnercontainer="grp_@groupId">
                <table data-grouped-id="@groupId" data-rebind-action="@Url.Action("RebindGroup", "AllLists")" class="table mb-0" @(group.AllListsSortColumn == AllListsSortColumn.Default ? "data-sortcol=" + (int)AllListsSortColumn.ListName + " data-sortdir=" + (int)group.SortDirection : "")>
                    <thead>
                        @if (group.Lists.Count == 1)
                    {
                        <tr>
                            <th scope="col" class="w-35">List name</th>
                            <th scope="col" class="w-20">User</th>
                            <th scope="col" class="w-20">Created date</th>
                            <th scope="col" class="w-10">Visibility</th>
                            <th scope="col" class="w-15"></th>
                        </tr>
                        }
                        else
                        {
                        <tr>
                            <th scope="col" class="w-35"><span class="sortable">List name <span class='@(group.AllListsSortColumn == AllListsSortColumn.Default ? "fa fa-sort-down" : "fa fa-sort")' title="Sort by Column" data-sortcol="@((int)AllListsSortColumn.ListName)"></span></span></th>
                            <th scope="col" class="w-20"><span class="sortable">User <span class="fa fa-sort" title="Sort by Column" data-sortcol="@((int)AllListsSortColumn.UserFullName)"></span></span></th>
                            <th scope="col" class="w-20"><span class="sortable">Created date <span class="fa fa-sort" title="Sort by Column" data-sortcol="@((int)AllListsSortColumn.CreatedDate)"></span></span></th>
                            <th scope="col" class="w-10">Visibility</th>
                            <th scope="col" class="w-15"></th>
                        </tr>

                        }
                    </thead>
                    <tbody data-grouped-id="@groupId">
                        @{ Html.RenderPartial("_ListsPartial", group); }
                    </tbody>
                </table>
            </div>
        </div>
    }
}

Medianet.Contacts.Web/Medianet.Contacts.Web/Views/AllLists/_ListsPartial.cshtml
@model Medianet.Contacts.Web.ViewModels.AllLists.ListsGroupedViewModel

@if (Model != null && Model.Lists != null)
{
    foreach (var item in Model.Lists)
    {
        <tr data-list-id="@item.ListId">
            <th scope="row">
                @Html.ActionLink(item.ListName, "Index", "List", new { ListId = item.ListId }, null)
            </th>
            <td>@item.UserFullName</td>
            <td>@item.CreatedDate.ToString("dd/MM/yyyy HH:mm")</td>
            <td>@item.Visibility</td>
            <td class="actionBtns text-right">
                <button data-edit class="btn btn-sm btn-link py-0" title="Edit List"
                        data-edit-action="@Url.Action("Edit", "List", new { listId = item.ListId })">
                    <i class="fal fa-pencil" aria-hidden="true"></i>
                </button>
                <button class="btn btn-sm btn-link py-0" data-id="@item.ListId" data-confirm="Delete list" data-confirm-text="@item.ListName" data-action="@Url.Action("DeleteList", "AllLists")"><i class="fal fa-times" aria-hidden="true"></i></button>
            </td>
        </tr>
    }
}